services:
  my-db:
    image: mysql
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: kiwidb
      MYSQL_USER: kiwi
      MYSQL_PASSWORD: kiwi
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-app
    depends_on:
      my-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://my-db:3306/kiwidb?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: kiwi
      SPRING_DATASOURCE_PASSWORD: kiwi
    ports:
      - "8000:8000"

volumes:
  mysql_data: